added some additional functions, started work on plugines, udpates aliases and bashrc
Why:

*

This change addresses the need by:

*

diff --git a/dfbin/dos2unix b/dfbin/dos2unix
--- a/dfbin/dos2unix
+++ b/dfbin/dos2unix
@@ -1,21 +1,46 @@
 #!/bin/bash
+##
+dry_run=false
+verbose=false
+TEMP=`getopt -o nhv --long dry-run,help -n 'example.bash' -- "$@"`
+# TEMP=`getopt -o a --long a-long,b-long:,c-long:: \
+#      -n 'example.bash' -- "$@"`
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true ; do
+  case "$1" in
+    -n|--dry-run) dry_run=true ; shift ;;
+    -h|--help) shift ;;
+    -v) verbose=true; shift ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+  esac
+done
+
 if [[ $# == 0 ]]; then
-    PDIR=`pwd`
+  PDIR=`pwd`
 else
-    PDIR=$1
-fi;
+  PDIR=$1
+fi
 
 ! [ -d "$PDIR" ] && echo "PDIR is not a directory" && exit
 
 function __convert() {
   f=$1
+  $dry_run && echo "would convert $f" && return || echo "converting $f";
   cp $f $f.orig && tr -d '\015' <$f >$f.conv && mv $f.conv $f && chmod +x $f;
   diff --strip-trailing-cr $f.orig $f && echo "output matches deleting tempfile" && rm $f.orig
 }
 
-for f in `find $PDIR -name "*" -type f`; do
+
+# for f in `find $PDIR -name "*" -type f`; do
+for f in `find $PDIR -type d \( -path $PDIR/.git \) -prune -o -print`; do
+  $verbose && echo $f
   file $f | grep CRLF &> /dev/null;
-  [[ $? == "0" ]] && echo "converting : $f" && __convert $f;
+  do_convert=$?
+  [[ $do_convert == "0" ]] && __convert $f;
 done;
 
 # for f in `find $PDIR -name "*" -type  f`; do
